FROM docker.io/library/alpine:latest
COPY ./build/Shmashmexa/backend/target/release /bin/shmashmexa
COPY ./build/Shmashmexa/frontend/build /var/www/internal/
CMD ["/bin/shmashmexa/shmashmexa-backend"]